### PR TITLE
UUID validation

### PR DESCRIPTION
**Pull request by mmuurr**
Hi, I've been using `uuid` to create UUIDs in R, and it's great.
But, I also have to verify UUIDs (as part of some data cleaning), and ended up using libuuid's `uuid_parse` function for a substantial speed-boost over relying on regexs.
I figured it'd be nice to include this extra functionality in the `uuid` package (without me forking the package and uploading a totally separate, but very similar package to CRAN... there's enough fragmentation of nearly-identical packages already :-)

The code additions/changes are fairly straight-forward, and I've included an example in the UUIDvalidate man page to demonstrate the speedup (over using `grepl`).

I'm also happy to help maintain the package if there are other ideas/features/etc. that you have, but are otherwise too busy to implement.

Cheers,

-Murat

### CODE REVIEW

**Comment by minimenchmuncher** [comment]
+1
I was actually just looking for this myself on CRAN.

**Comment by agower** [comment]
Your speed increase is impressive, but I'm curious to know why you have found it necessary for your specific application, as grepl is already extremely fast (according to your speed test, grepl can validate 1 million UUIDs in ~2.5 sec).

**Comment by mmuurr** [comment]
Truthfully, I don't recall the exact implementation constraint where I found speed issues, but (now a few years later) I still think this is a useful addition for this reason: the 'authoritative' validation code path executes through libuuid. This way if libuuid changes any validation procedures (or accommodates any future UUID spec changes), no R code would have to algorithmically 'match' those changes.

EDIT: I went through my old code and found the use case: I was reading files with ~100 million UUIDs and I'm impatient :-P

**Comment by s-u** [comment]
Thanks, very good idea, I have finally come around to adding interfaces to parse and native UUID representation, so this is now supported in uuid version 1.1 (added in ce03b804).

**Pull request closed without merging**
